name: Replace repo_url
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Find and Replace
      uses: shitiomatic/str-replace@master
      with:
        find: "repo_url"
        replace: GITHUB_SERVER_URL +"/"+ GITHUB_REPOSITORY
        include: "*.md"